#!/bin/bash
LINK_MODEL=$1
MODEL_NAME=`basename $LINK_MODEL`
if [[ -n "$HF_TOKEN" ]];then
wget --header="Authorization: Bearer $HF_TOKEN" -O /Models/$MODEL_NAME $LINK_MODEL
exit
fi
wget -O /Models//$MODEL_NAME $LINK_MODEL
